import 'package:material_ui/material_ui.dart';
import 'package:picons/picons.dart';

import '../../core/ui/views.dart';
import '../../l10n/app_localizations.dart';

/// The Hosts destination.
///
/// Returns body content, not a [Scaffold]: the app shell owns the Scaffold,
/// the AppBar and the navigation chrome, so a destination only says what goes
/// inside. A full page pushed *over* the shell (see `AboutScreen`) does bring
/// its own Scaffold.
///
/// Generated by beej as a placeholder — replace the body, keep the location.
class HostsScreen extends StatelessWidget {
  const HostsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return EmptyView(
      icon: PiconsRegular.circle,
      title: l10n.comingSoon,
      message: l10n.comingSoonBody,
    );
  }
}
