import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Release signing, loaded from android/key.properties when that file exists.
// It is gitignored and generated by keytool. Keys: storeFile, storePassword,
// keyAlias, keyPassword. Without it the release build falls back to debug
// signing, so `flutter run --release` still works for anyone without the
// keystore — which is every fresh clone and every CI job that only builds.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
val hasReleaseKeystore = keystorePropertiesFile.exists()
if (hasReleaseKeystore) {
    keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
}

android {
    namespace = "com.popupbits.sshetu"
    // Pinned above `flutter.compileSdkVersion` (36 on this Flutter release).
    // flutter_secure_storage's AAR declares a minimum compileSdk of 37, and
    // the build fails outright rather than degrading:
    //
    //   Dependency ':flutter_secure_storage' requires libraries and
    //   applications that depend on it to compile against version 37 or later
    //   of the Android APIs. :app is currently compiled against android-36.
    //
    // Compiling against a newer SDK does not change what the app runs on —
    // minSdk and targetSdk below still decide that — so this raises the
    // compile-time API surface only. Drop the override once Flutter's own
    // default reaches 37.
    compileSdk = 37
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.popupbits.sshetu"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        // The launcher label. The manifest reads it, so the debug build type
        // below can rename itself without the release manifest changing.
        manifestPlaceholders["appLabel"] = "SSHetu"
    }

    signingConfigs {
        if (hasReleaseKeystore) {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
                storeFile = (keystoreProperties["storeFile"] as String?)?.let { file(it) }
                storePassword = keystoreProperties["storePassword"] as String
            }
        }
    }

    buildTypes {
        // Debug builds are their own app, "SSHetu Debug": a separate package
        // (com.popupbits.sshetu.debug), so a debug install never opens the
        // real one's database, preferences or keystore entries, and installs
        // beside it. Release and profile keep defaultConfig's applicationId
        // untouched — that id is what every existing install's data is filed
        // under. Guarded by test/android_identity_test.dart; see PROJECT.md,
        // "Debug builds have their own identity".
        debug {
            applicationIdSuffix = ".debug"
            manifestPlaceholders["appLabel"] = "SSHetu Debug"
        }
        // The Flutter plugin creates `profile` with initWith(debug) when it is
        // applied, before this block runs, so it does not inherit the suffix
        // today. Said explicitly anyway: profile builds are release-shaped
        // and must never become a third identity through an ordering change.
        getByName("profile") {
            applicationIdSuffix = null
            manifestPlaceholders["appLabel"] = "SSHetu"
        }
        release {
            signingConfig = if (hasReleaseKeystore) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
